import { fireEvent, render, screen, waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { afterEach, beforeEach, describe, expect, it } from 'vitest'
import { cleanup } from '@testing-library/react'
import App from './App'

describe('player menu', () => {
  beforeEach(() => { localStorage.clear(); window.location.hash = '' })
  afterEach(() => cleanup())
  it('derives crystal duty from the selected assignment and starts with a countdown', async () => { const user = userEvent.setup(); render(<App />); fireEvent.change(screen.getByLabelText(/assignment position/i), { target: { value: '1' } }); expect(screen.getByRole('button', { name: /crystal assigned/i })).toBeInTheDocument(); await user.click(screen.getByRole('button', { name: /enter arena/i })); expect(screen.getByText(/Get ready/i)).toBeInTheDocument(); expect(screen.getByText('3')).toBeInTheDocument(); expect(screen.getByText(/CRYSTAL CARRIER/i)).toBeInTheDocument(); expect(screen.getByText('Points')).toBeInTheDocument(); expect(document.querySelector('.hud')).not.toBeInTheDocument() })
  it('shows the assignment control and difficulty choices', () => { render(<App />); expect(screen.getByLabelText(/assignment position/i)).toBeInTheDocument(); expect(screen.getByRole('button', { name: 'easy' })).toBeInTheDocument(); expect(screen.getByRole('button', { name: 'hard' })).toBeInTheDocument() })
  it('shows P3 and P4 as unavailable future practice targets', () => { render(<App />); expect(screen.getByRole('button', { name: /p3 — coming soon/i })).toBeDisabled(); expect(screen.getByRole('button', { name: /p4 — coming soon/i })).toBeDisabled() })
  it('explains recoverable wipes outside Hard mode', async () => { const user = userEvent.setup(); render(<App />); expect(screen.getByText(/first wipe costs 500 points/i)).toBeInTheDocument(); await user.click(screen.getByRole('button', { name: 'hard' })); expect(screen.getByText(/wipe ends the attempt immediately/i)).toBeInTheDocument() })
  it('assigns a name and WoW class color and saves all profiles', async () => { const user = userEvent.setup(); render(<App />); await user.clear(screen.getByLabelText(/player name/i)); await user.type(screen.getByLabelText(/player name/i), 'Lunara'); await user.selectOptions(screen.getByLabelText(/player class and color/i), 'mage'); await user.click(screen.getByRole('button', { name: /save layout/i })); const saved = JSON.parse(localStorage.getItem('lura-player-profiles') || '[]'); expect(saved).toHaveLength(20); expect(saved[0]).toMatchObject({ name: 'Lunara', playerClass: 'mage', crystal: false }) })
  it('shows four configurable raid-plan start slots and saves them', async () => { const user = userEvent.setup(); render(<App />); expect(screen.getAllByRole('button', { name: /start slot/i })).toHaveLength(4); await user.click(screen.getByRole('button', { name: /save layout/i })); expect(JSON.parse(localStorage.getItem('lura-start-slots') || '[]')).toHaveLength(4) })
  it('creates a shareable raid-plan link and supports P pause/resume', async () => { const user = userEvent.setup(); render(<App />); await user.click(screen.getByRole('button', { name: /copy share link/i })); expect((screen.getByLabelText(/raid plan share code/i) as HTMLInputElement).value).toContain('#raidplan='); await user.click(screen.getByRole('button', { name: /enter arena/i })); await user.keyboard('p'); expect(screen.getByRole('button', { name: /resume/i })).toBeInTheDocument(); await user.keyboard('p'); expect(screen.getByRole('button', { name: /^pause$/i })).toBeInTheDocument() })
  it('loads a raid plan when the hash changes without a page reload', async () => { const user = userEvent.setup(); render(<App />); const name = screen.getByLabelText(/player name/i); await user.clear(name); await user.type(name, 'Shared Player'); await user.click(screen.getByRole('button', { name: /copy share link/i })); const link = (screen.getByLabelText(/raid plan share code/i) as HTMLInputElement).value; await user.clear(name); await user.type(name, 'Local Player'); window.location.hash = new URL(link).hash; await waitFor(() => expect(name).toHaveValue('Shared Player')); expect(screen.getByText('Shared raid plan loaded')).toBeInTheDocument() })
  it('explains the independent look, facing, and zoom controls', async () => { const user = userEvent.setup(); render(<App />); await user.click(screen.getByRole('button', { name: /enter arena/i })); expect(screen.getByText(/left-drag look · right-drag view \+ face · wheel zoom/i)).toBeInTheDocument() })
  it('shows zoom information in the bottom status bar instead of over the arena', async () => { const user = userEvent.setup(); render(<App />); await user.click(screen.getByRole('button', { name: /enter arena/i })); expect(screen.getByText(/Zoom 16\.0 yd/i)).toHaveClass('controls'); expect(document.querySelector('.zoom-readout')).not.toBeInTheDocument() })
  it('offers the opening boost and main ability in every mode but disables health reactions on Easy', async () => { const user = userEvent.setup(); render(<App />); expect(screen.getByLabelText(/opening movement bonus/i)).toBeEnabled(); await user.click(screen.getByRole('button', { name: 'easy' })); expect(screen.getByLabelText(/opening movement bonus/i)).toBeEnabled(); expect(screen.getByLabelText(/enable health potion/i)).toBeDisabled(); expect(screen.getByLabelText(/enable shield/i)).toBeDisabled(); expect(screen.getByLabelText(/enable main ability/i)).toBeEnabled() })
  it('rebinds gameplay actions and displays the optional health HUD', async () => { const user = userEvent.setup(); render(<App />); const forward = screen.getByLabelText(/forward keybind/i); fireEvent.keyDown(forward, { code: 'KeyI', key: 'i' }); expect(forward).toHaveValue('I'); await waitFor(() => expect(JSON.parse(localStorage.getItem('lura-keybindings') || '{}').forward).toBe('KeyI')); await user.click(screen.getByLabelText(/enable health potion/i)); await user.click(screen.getByRole('button', { name: /enter arena/i })); expect(screen.getByText(/100%/i)).toBeInTheDocument(); expect(screen.getByText(/Q POT/i)).toBeInTheDocument() })
  it('persists and displays the global simulation speed', async () => { const user = userEvent.setup(); render(<App />); fireEvent.change(screen.getByLabelText(/global game speed/i), { target: { value: '2' } }); await waitFor(() => expect(localStorage.getItem('lura-game-speed')).toBe('2')); await user.click(screen.getByRole('button', { name: /enter arena/i })); expect(screen.getByText(/2\.00×/i)).toBeInTheDocument() })
  it('provides and saves separate twenty-player Phase 2 soak and spread assignments', async () => { const user = userEvent.setup(); render(<App />); expect(screen.getByLabelText(/phase 2 soak position map/i)).toBeInTheDocument(); expect(screen.getByLabelText(/phase 2 spread position map/i)).toBeInTheDocument(); expect(screen.getAllByRole('button', { name: /move p2 soak player/i })).toHaveLength(20); expect(screen.getAllByRole('button', { name: /move p2 spread player/i })).toHaveLength(20); await user.click(screen.getByRole('button', { name: /save layout/i })); expect(JSON.parse(localStorage.getItem('lura-p2-player-positions') || '[]')).toHaveLength(20); expect(JSON.parse(localStorage.getItem('lura-p2-spread-positions') || '[]')).toHaveLength(20) })
  it('shows mechanic-sized personal circles on every P2 spread assignment', () => { render(<App />); const spreadMap = screen.getByLabelText(/phase 2 spread position map/i); const rings = spreadMap.querySelectorAll<HTMLElement>('.planner-personal-circle'); expect(rings).toHaveLength(20); expect(parseFloat(rings[0].style.width)).toBeCloseTo(7.2814, 3); expect(screen.getByLabelText(/phase 2 soak position map/i).querySelectorAll('.planner-personal-circle')).toHaveLength(0) })
  it('shows Pestivator attribution and working Solana support details', async () => { const user = userEvent.setup(); render(<App />); const card = screen.getByLabelText(/about pestivator/i); expect(card).toHaveTextContent('pestivator#2515'); expect(screen.getByRole('link', { name: 'Twitch' })).toHaveAttribute('href', 'https://twitch.tv/pestivator'); expect(screen.getByRole('link', { name: /buy me a coffee/i })).toHaveAttribute('href', expect.stringContaining('E684K1q1gzodtZK3xgdBXfTeRQbWWhSu8kVbzZNiw9Cz')); const copy = screen.getByRole('button', { name: /copy solana address/i }); expect(copy).toHaveAttribute('title', 'E684K1q1gzodtZK3xgdBXfTeRQbWWhSu8kVbzZNiw9Cz'); await user.click(copy); expect(screen.getByRole('button', { name: /sol address copied/i })).toBeInTheDocument(); expect(screen.getByAltText(/gnome avatar/i)).toBeInTheDocument() })
  it('loads, resets, and persists the draggable HUD layout including the castbar', async () => { localStorage.setItem('lura-hud-layout', JSON.stringify({ mechanic: { x: 22, y: 18 }, beam: { x: 72, y: 31 }, crystal: { x: 66, y: 82 } })); const user = userEvent.setup(); render(<App />); expect(screen.getByLabelText(/phase 2 hud layout preview/i)).toBeInTheDocument(); expect(screen.getByRole('button', { name: /move beam in counter/i })).toHaveStyle({ left: '72%', top: '31%' }); expect(screen.getByRole('button', { name: /move player health counter/i })).toHaveStyle({ left: '50%', top: '86%' }); expect(screen.getByRole('button', { name: /move main ability counter/i })).toHaveStyle({ left: '50%', top: '66%' }); await user.click(screen.getByRole('button', { name: /reset counter positions/i })); expect(screen.getByRole('button', { name: /move beam in counter/i })).toHaveStyle({ left: '50%', top: '39%' }); await waitFor(() => expect(JSON.parse(localStorage.getItem('lura-hud-layout') || '{}').castbar).toEqual({ x: 50, y: 66 })) })
  it('casts the optional main ability once per second for points without killing the boss', async () => { const user = userEvent.setup(); render(<App />); await user.click(screen.getByLabelText(/enable main ability/i)); await user.click(screen.getByRole('button', { name: /enter arena/i })); fireEvent.keyDown(window, { code: 'KeyF', key: 'f' }); expect(screen.getByText(/L’URA · 99\.5%/i)).toBeInTheDocument(); expect(screen.getByText(/MAIN ABILITY · 1\.0s/i)).toBeInTheDocument(); expect(screen.getByText('Points').nextElementSibling).toHaveTextContent('1001'); fireEvent.keyDown(window, { code: 'KeyF', key: 'f' }); expect(screen.getByText('Points').nextElementSibling).toHaveTextContent('1001') })
  it('moves newly assigned crystal carriers onto an inner P2 spread spot', async () => { const user = userEvent.setup(); render(<App />); await user.click(screen.getByRole('button', { name: /no crystal/i })); await waitFor(() => expect(screen.getByRole('button', { name: /crystal assigned/i })).toBeInTheDocument()); await user.click(screen.getByRole('button', { name: /save layout/i })); const [spot] = JSON.parse(localStorage.getItem('lura-p2-spread-positions') || '[]'); expect(Math.hypot(spot.x - 480, spot.y - 270)).toBeLessThanOrEqual(46.01) })
  it('can enter P2 directly with its own countdown and compact arena HUD', async () => { const user = userEvent.setup(); render(<App />); await user.click(screen.getByRole('button', { name: /^P2$/ })); await user.click(screen.getByRole('button', { name: /enter p2/i })); expect(screen.getByText(/Get ready for Phase 2/i)).toBeInTheDocument(); expect(screen.getByText(/PHASE 2 · CYCLE 1 \/ 3/i)).toBeInTheDocument(); expect(screen.getByText(/raid begins stacked in the middle/i)).toBeInTheDocument(); expect(screen.getByText('Points')).toBeInTheDocument() })
  it('defaults to 20% music, previews tracks, persists sound settings, and offers an arena mute button', async () => { const user = userEvent.setup(); render(<App />); expect(screen.getByLabelText(/background music volume/i)).toHaveValue('0.2'); expect(screen.getByLabelText(/background music track/i)).toHaveValue('panic'); await user.click(screen.getByRole('button', { name: /play preview/i })); expect(screen.getByRole('button', { name: /stop preview/i })).toBeInTheDocument(); await user.click(screen.getByRole('button', { name: /stop preview/i })); fireEvent.change(screen.getByLabelText(/background music volume/i), { target: { value: '.35' } }); await user.selectOptions(screen.getByLabelText(/background music track/i), 'dominion'); await user.click(screen.getByLabelText(/mute background music/i)); expect(screen.getByRole('button', { name: /unmute to preview/i })).toBeDisabled(); await waitFor(() => { expect(localStorage.getItem('lura-music-volume')).toBe('0.35'); expect(localStorage.getItem('lura-music-track')).toBe('dominion'); expect(localStorage.getItem('lura-music-muted')).toBe('true') }); await user.click(screen.getByRole('button', { name: /enter arena/i })); const unmute = screen.getByRole('button', { name: /unmute music/i }); expect(unmute).toHaveTextContent(/muted/i); await user.click(unmute); expect(screen.getByRole('button', { name: /mute music/i })).toBeInTheDocument() })
  it('migrates the old Space pause binding to Space jump and P pause', () => { localStorage.setItem('lura-keybindings', JSON.stringify({ forward: 'KeyW', backward: 'KeyS', left: 'KeyA', right: 'KeyD', crystal: 'KeyE', pause: 'Space', healthPot: 'KeyQ', shield: 'KeyR', mainAbility: 'KeyF' })); render(<App />); expect(screen.getByLabelText(/jump keybind/i)).toHaveValue('Space'); expect(screen.getByLabelText(/pause \/ resume keybind/i)).toHaveValue('P') })
})
