import { describe, expect, it } from 'vitest'
import { ARENA, assignmentRevealDistance, bossBeamHitsPlayer, canPickupCrystal, canRecoverFromWipe, crystalCarrierPosition, crystalWipeReason, difficultySettings, distance, healthEmergencyLimit, INTERMISSION_SEQUENCE, isInSafeAnnulus, isInsideArena, moveInBounds, movePlayer, moveRelativeToCamera, moveWithIncreasingPull, npcEntryPosition, OPENING_BOOST_SECONDS, orientedAssignments, PLAYER_COLLISION_PENALTY, roamingNpcPosition, seededStars, WIPE_PENALTY } from './game'

describe('Intermission game rules', () => {
  it('creates six deterministic stars for a seed', () => { expect(seededStars(42)).toEqual(seededStars(42)); expect(seededStars(42)).toHaveLength(6) })
  it('moves with normalized WASD input and keeps the player in bounds', () => { const p = movePlayer({ x: 20, y: 20 }, new Set(['w', 'a']), 200, 1); expect(p.x).toBe(24); expect(p.y).toBe(24) })
  it('moves continuously in zoomed world coordinates without adding a camera offset', () => { const bounds = { minX: 30, maxX: 1070, minY: 30, maxY: 790 }; expect(moveInBounds({ x: 550, y: 410 }, new Set(['d']), 100, .5, bounds)).toEqual({ x: 600, y: 410 }); expect(moveInBounds({ x: 600, y: 410 }, new Set(), 100, .5, bounds)).toEqual({ x: 600, y: 410 }) })
  it('recognizes the safe arena ring', () => { expect(isInsideArena(ARENA.center)).toBe(true); expect(isInsideArena({ x: 10, y: 10 })).toBe(false); expect(distance(ARENA.center, ARENA.center)).toBe(0) })
  it('makes hard mode faster and easy mode assisted', () => { expect(difficultySettings('hard').speed).toBeGreaterThan(difficultySettings('normal').speed); expect(difficultySettings('easy').helper).toBe(true) })
  it('alternates three-second beam and Starsplinter packs without an idle gap', () => { expect(INTERMISSION_SEQUENCE.map(step => step.kind)).toEqual(['beam', 'splinter']); expect(INTERMISSION_SEQUENCE.map(step => step.seconds)).toEqual([3, 3]) })
  it('only treats the band between the two arena circles as safe', () => { const center = { x: 100, y: 100 }; expect(isInSafeAnnulus({ x: 160, y: 100 }, center, 50, 80)).toBe(true); expect(isInSafeAnnulus({ x: 120, y: 100 }, center, 50, 80)).toBe(false); expect(isInSafeAnnulus({ x: 190, y: 100 }, center, 50, 80)).toBe(false) })
  it('maps forward and strafe movement to the camera direction', () => { const bounds = { minX: 0, maxX: 1000, minY: 0, maxY: 1000 }; expect(moveRelativeToCamera({ x: 500, y: 500 }, new Set(['w']), 100, 1, { x: 0, y: -1 }, bounds)).toEqual({ x: 500, y: 400 }); expect(moveRelativeToCamera({ x: 500, y: 500 }, new Set(['d']), 100, 1, { x: 0, y: -1 }, bounds)).toEqual({ x: 600, y: 500 }) })
  it('allows movement against the early pull but overwhelms it at full force', () => { const bounds = { minX: 0, maxX: 1000, minY: 0, maxY: 1000 }; const start = { x: 600, y: 500 }; const center = { x: 500, y: 500 }; expect(moveWithIncreasingPull(start, new Set(['w']), 15, 1, { x: 1, y: 0 }, bounds, center, 0).x).toBeGreaterThan(start.x); expect(moveWithIncreasingPull(start, new Set(['w']), 15, 1, { x: 1, y: 0 }, bounds, center, 1).x).toBeLessThan(start.x) })
  it('requires the crystal to unlock and the player to move closer than simple model contact', () => { const crystal = { x: 100, y: 100 }; expect(canPickupCrystal({ x: 100, y: 100 }, crystal, .9)).toBe(false); expect(canPickupCrystal({ x: 104, y: 100 }, crystal, 2)).toBe(false); expect(canPickupCrystal({ x: 102.9, y: 100 }, crystal, 2)).toBe(true) })
  it('only resolves a boss beam against the player at the end of its telegraph', () => { const origin = { x: 0, y: 0 }; const player = { x: 100, y: 0 }; expect(bossBeamHitsPlayer(player, origin, [0], 12, 2.5)).toBe(false); expect(bossBeamHitsPlayer(player, origin, [0], 12, 2.9)).toBe(true); expect(bossBeamHitsPlayer({ x: 100, y: 20 }, origin, [0], 12, 2.9)).toBe(false) })
  it('moves NPCs out of boss lines and returns crystal carriers to their drop', () => { const center = { x: 0, y: 0 }; const base = { x: 100, y: 0 }; const idle = roamingNpcPosition(base, 0, 0, 'positioning', 2, [0], center); const dodging = roamingNpcPosition(base, 0, 0, 'beam', 2, [0], center); expect(Math.abs(dodging.y)).toBeGreaterThan(Math.abs(idle.y)); const away = crystalCarrierPosition(base, base, 2, 0, center); const returned = crystalCarrierPosition(base, base, 5, 0, center); expect(distance(away, base)).toBeGreaterThan(15); expect(distance(returned, base)).toBeLessThan(.01) })
  it('treats a missed drop, a crystal hit, and an expired pickup as 500-point wipes', () => { expect(WIPE_PENALTY).toBe(500); expect(crystalWipeReason({ assigned: true, splinterResolving: true, dropped: false, crystalHit: false, expired: false })).toMatch(/before you dropped/i); expect(crystalWipeReason({ assigned: true, splinterResolving: true, dropped: true, crystalHit: true, expired: false })).toMatch(/hit your crystal/i); expect(crystalWipeReason({ assigned: true, splinterResolving: false, dropped: true, crystalHit: false, expired: true })).toMatch(/expired/i); expect(crystalWipeReason({ assigned: false, splinterResolving: true, dropped: false, crystalHit: false, expired: false })).toBeNull() })
  it('rotates assignments from the South reference while leaving world markers independent', () => { const center = { x: 0, y: 0 }; const assignment = [{ x: 0, y: 10 }]; expect(orientedAssignments(assignment, { x: 0, y: -20 }, center)[0].y).toBeCloseTo(-10); expect(orientedAssignments(assignment, { x: 20, y: 0 }, center)[0].x).toBeCloseTo(10) })
  it('moves NPCs from the chosen entry toward their assignment at configured speed', () => { const target = { x: 100, y: 0 }; const start = { x: 0, y: 0 }; expect(npcEntryPosition(target, start, 0, 1, 20)).toEqual({ x: 20, y: 0 }); expect(npcEntryPosition(target, start, 0, 10, 20)).toEqual(target) })
  it('uses 500-point crystal wipes and 50-point player collisions', () => { expect(WIPE_PENALTY).toBe(500); expect(PLAYER_COLLISION_PENALTY).toBe(50) })
  it('lets Easy and Normal recover from the first wipe while Hard ends immediately', () => { expect(canRecoverFromWipe('easy', 1, 1000, WIPE_PENALTY)).toBe(true); expect(canRecoverFromWipe('normal', 1, 1000, WIPE_PENALTY)).toBe(true); expect(canRecoverFromWipe('normal', 2, 500, WIPE_PENALTY)).toBe(false); expect(canRecoverFromWipe('hard', 1, 1000, WIPE_PENALTY)).toBe(false) })
  it('caps health emergencies across the whole run by difficulty', () => { expect(healthEmergencyLimit('easy')).toBe(0); expect(healthEmergencyLimit('normal')).toBe(1); expect(healthEmergencyLimit('hard')).toBe(2) })
  it('uses a five-second opening boost and tighter assignment reveals by difficulty', () => { expect(OPENING_BOOST_SECONDS).toBe(5); expect(assignmentRevealDistance('easy')).toBe(Infinity); expect(assignmentRevealDistance('normal')).toBe(45); expect(assignmentRevealDistance('hard')).toBe(22) })
})
